config/routes.rb
require 'year_constraint'
require 'api_constraints'

Rails.application.routes.draw do
  default_url_options protocol: '//' # HTTP o HTTPS
  default_url_options host: Rails.application.secrets.rails_host

  namespace :api, defaults: {format: :json}, except: [:new, :edit] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :nota_entradas, only: [:index] do
        put :anular, on: :member
      end

      resources :solicitudes, only: [:index] do
        put :anular, on: :member
      end

      resources :users, only: [:obt_historico_actas] do
        get :obt_historico_actas, on: :member
        get :obt_activos, on: :member
      end

      resources :reportes, only: [:activos] do
        get :activos, on: :collection
      end

      resources :seguros, only: [:create, :update]

      resources :proveedores, only: [:index]

      resources :activos, only: [:index] do
        get :sin_seguro_vigente, on: :member
      end

      resources :requests, only: [:show] do
        post :validar_cantidades, on: :member
      end

      resources :auxiliares, only: [:show]

      resources :accounts, only: [:show]

      resources :suppliers, only: [:show]
    end
  end

  resources :gestiones, except: [:destroy] do
    put 'cerrar', on: :member
  end
  resources :ufvs, except: [:show, :destroy]
  resources :ubicaciones, except: [:show, :destroy]
  resources :ingresos do
    get :obt_cod_ingreso, on: :collection
  end

  resources :reportes do
    collection do
      get :kardex
      get :activos
      get :depreciacion
      get :resumen
      get :cuenta_contable
      get :estadisticas
      get :bajas
    end
  end

  resources :entry_subarticles, only: [:edit, :update]

  resources :almacenes, only: [:index]

  resources :note_entries, except: [:destroy] do
    get :get_suppliers, on: :collection
    get :obt_cod_ingreso, on: :collection
  end

  resources :suppliers do
    get :note_entries, on: :member
    get :ingresos, on: :member
  end

  resources :accounts do
    get :auxiliares, on: :member
    get :activos, on: :member
  end

  resources :seguros do
    get :asegurar, on: :member
    get :incorporaciones, on: :member
    get :activos, on: :member
    get :resumen, on: :member
  end

  resources :bajas, only: [:index, :new, :create, :show, :edit]

  resources :requests, except: [:edit, :destroy] do
    get :obtiene_nro_solicitud, on: :collection
  end

  resources :materials, except: [:destroy] do
    post :change_status, on: :member
    get :reports, on: :collection
  end

  resources :subarticles, except: [:destroy] do
    resources :kardexes, only: [:index]
    member do
      post :change_status
    end
    collection do
      get :get_subarticles
      get :autocomplete
      post :first_entry
    end
  end

  resources :barcodes, only: [:index] do
    collection do
      get :obt_cod_barra
      post :pdf
    end
  end

  resources :proceedings, only: [:index, :show, :create, :update]

  resources :declines, only: [:index]

  resources :versions, only: [:index] do
    post :export, on: :collection
  end

  resources :assets, except: [:destroy] do
    member do
      get :historical
      get :depreciacion
    end
    collection do
      get :autocomplete
      get :admin_assets
      get :search
      get :assignation
      get :devolution
      get :users
      get :departments
    end
  end

  resources :auxiliaries, except: [:destroy] do
    post :change_status, on: :member
    get :activos, on: :member
  end

  resources :accounts, only: [:index, :show]

  resources :departments, except: [:destroy] do
    post :change_status, on: :member
    get :download, on: :member
  end

  resources :buildings, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :entities

  resources :users, except: [:destroy] do
    post :change_status, on: :member
    get :welcome, on: :collection
    get :download, on: :member
    get :autocomplete, on: :collection
    get :historical, on: :member
  end

  get '/datatables-spanish', to: 'welcome#datatables_spanish', as: :spanish_datatables
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  patch '/dashboard/update_password', to: 'dashboard#update_password', as: :update_password_dashboard
  post '/dashboard/announcements/hide', to: 'dashboard#hide', as: :hide_announcement

  post '/dbf/:model/import', to: 'dbf#import', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'import_dbf'
  get '/dbf/:model', to: 'dbf#index', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'dbf'
  get '/dbf', to: redirect("#{ Rails.application.config.action_controller.relative_url_root }/dbf/buildings"), as: 'migration'

  devise_for :users, controllers: { sessions: "sessions" }, skip: [ :sessions ]
  as :user do
    get '/login' => 'sessions#new', as: :new_user_session
    post '/login' => 'sessions#create', as: :user_session
    delete '/logout' => 'sessions#destroy', as: :destroy_user_session
  end

  resources :welcome, only: [:index]

  root 'users#welcome'
end

app/models/ingreso.rb
class Ingreso < ActiveRecord::Base
  include Autoincremento

  default_scope -> { where(baja_logica: false) }

  scope :del_anio_por_fecha_factura, -> (fecha) { where(factura_fecha: fecha.beginning_of_year..fecha.end_of_year) }
  scope :mayor_a_fecha_factura, -> (fecha) { where('factura_fecha > ?', fecha) }
  scope :menor_igual_a_fecha_factura, -> (fecha) { where('factura_fecha <= ?', fecha) }
  scope :con_fecha_factura, -> { where.not('factura_fecha is null') }
  scope :con_numero, -> { where('numero is not null')}

  belongs_to :supplier
  has_many :assets
  belongs_to :user

  def self.array_model(sort_column, sort_direction, page, per_page, sSearch, search_column, current_user = '')
    orden = "#{sort_column} #{sort_direction}"
    case sort_column
    when "ingresos.factura_fecha"
      orden += ", ingresos.numero #{sort_direction}, ingresos.incremento_alfabetico #{sort_direction}"
    when "ingresos.numero"
      orden += ", ingresos.incremento_alfabetico #{sort_direction}"
    end
    array = joins(:user, :supplier).order(orden)
    array = array.page(page).per_page(per_page) if per_page.present?
    if sSearch.present?
      if search_column.present?
        type_search = %w(users suppliers).include?(search_column) ? "#{search_column}.name" : "ingresos.#{search_column}"
        array = array.where("#{type_search} like :search", search: "%#{sSearch}%")
      else
        array = array.where("ingresos.factura_fecha LIKE ? OR ingresos.numero LIKE ? OR ingresos.factura_numero LIKE ? OR suppliers.name LIKE ? OR users.name LIKE ? OR ingresos.total LIKE ?", "%#{sSearch}%", "%#{sSearch}%", "%#{sSearch}%", "%#{sSearch}%", "%#{sSearch}%", "%#{sSearch}%")
      end
    end
    array
  end

  def self.set_columns
    h = ApplicationController.helpers
    [h.get_column(self, 'numero'), h.get_column(self, 'factura_fecha'), h.get_column(self, 'factura_numero'), h.get_column(self, 'supplier'), h.get_column(self, 'users'), h.get_column(self, 'total'), h.get_column(self, 'nota_entrega_fecha')]
  end

  def self.to_csv
    columns = %w(numero factura_fecha factura_numero supplier telefono users total nota_entrega_fecha)
    h = ApplicationController.helpers
    CSV.generate do |csv|
      csv << columns.map { |c| Ingreso.human_attribute_name(c) }
      all.each do |ingreso|
        a = Array.new
        a << ingreso.numero
        a << ingreso.factura_fecha
        a << ingreso.factura_numero
        a << ingreso.supplier_name
        a << ingreso.telefono_proveedor
        a << ingreso.user_name
        a << ingreso.total
        a << ingreso.nota_entrega_fecha
        csv << a
      end
    end
  end

  # Método para obtener las gestiones involucradas de los ingresos generados.
  def self.obtiene_gestiones
    Ingreso.select('extract(year from factura_fecha) as gestion')
           .group('extract(year from factura_fecha)')
           .order('extract(year from factura_fecha) asc')
  end

  def supplier_name
    supplier.present? ? supplier.name : ''
  end

  def supplier_nit
    supplier.present? ? supplier.nit : ''
  end

  def supplier_telefono
    supplier.present? ? supplier.telefono : ''
  end

  def user_name
    user.present? ? user.name : ''
  end

  def telefono_proveedor
    supplier.telefono
  end

  def obtiene_numero
    if !incremento_alfabetico.present?
      "#{numero}"
    else
      "#{numero}-#{incremento_alfabetico}"
    end
  end

  def self.numero_ingreso_anterior(fecha)
    fecha = fecha.to_date
    self.del_anio_por_fecha_factura(fecha).menor_igual_a_fecha_factura(fecha).con_numero.maximum(:numero)
  end

  def self.numero_ingreso_posterior(fecha)
    fecha = fecha.to_date
    self.del_anio_por_fecha_factura(fecha).mayor_a_fecha_factura(fecha).con_numero.minimum(:numero)
  end

  def tiene_numero?
    numero.present? && factura_numero.present?
  end

  def self.numero_ingreso_posterior_regularizado(fecha)
    fecha = fecha.to_date
    numero = self.numero_ingreso_anterior(fecha)
    self.del_anio_por_fecha_factura(fecha).mayor_a_fecha_factura(fecha).where(numero: numero).first.try(:incremento_alfabetico)
  end

  def self.obtiene_siguiente_numero_ingreso(fecha)
    codigo_numerico = nil
    codigo_alfabetico = nil
    respuesta_hash = Hash.new
    if fecha.present?
      fecha = fecha.to_date
      numero_ingreso_anterior = Ingreso.numero_ingreso_anterior(fecha)
      numero_ingreso_posterior = Ingreso.numero_ingreso_posterior(fecha)
      if numero_ingreso_anterior.present? && !numero_ingreso_posterior.present?
        respuesta_hash[:codigo_numerico] = numero_ingreso_anterior.to_i + 1
      elsif !numero_ingreso_anterior.present? && !numero_ingreso_posterior.present?
        respuesta_hash[:codigo_numerico] = 1
      elsif numero_ingreso_anterior.present? && numero_ingreso_posterior.present?
        diferencia = numero_ingreso_posterior - numero_ingreso_anterior
        if diferencia > 1
          respuesta_hash[:codigo_numerico] = numero_ingreso_anterior.to_i + 1
        else
          inc_alfabetico = Ingreso.numero_ingreso_posterior_regularizado(fecha)
          if inc_alfabetico.present?
            ingreso_anterior = Ingreso.del_anio_por_fecha_factura(fecha).con_numero.menor_igual_a_fecha_factura(fecha).order(factura_fecha: :desc, numero: :desc, incremento_alfabetico: :desc).first
            ingreso_posterior = Ingreso.del_anio_por_fecha_factura(fecha).con_numero.mayor_a_fecha_factura(fecha).order(factura_fecha: :asc, numero: :asc, incremento_alfabetico: :asc).first
            respuesta_hash[:tipo_respuesta] = "alerta"
            respuesta_hash[:fecha] = fecha.strftime("%d/%m/%Y")
            respuesta_hash[:numero_ingreso_anterior] = ingreso_anterior.obtiene_numero
            respuesta_hash[:fecha_ingreso_anterior] = ingreso_anterior.factura_fecha.strftime("%d/%m/%Y") if ingreso_anterior.factura_fecha.present?
            respuesta_hash[:numero_ingreso_posterior] =  ingreso_posterior.obtiene_numero
            respuesta_hash[:fecha_ingreso_posterior] = ingreso_posterior.factura_fecha.strftime("%d/%m/%Y") if ingreso_posterior.factura_fecha.present?
          else
            max_incremento_alfabetico = Ingreso.where(numero: numero_ingreso_anterior).order(incremento_alfabetico: :desc).first.incremento_alfabetico
            codigo_numerico = numero_ingreso_anterior.to_i
            codigo_alfabetico = max_incremento_alfabetico.present? ? max_incremento_alfabetico.next : "A"
            ultima_fecha = Ingreso.del_anio_por_fecha_factura(fecha).order(factura_fecha: :desc).first.try(:factura_fecha)
            ultima_fecha = ultima_fecha.strftime("%d/%m/%Y") if ultima_fecha.present?
            respuesta_hash[:tipo_respuesta] = "confirmacion"
            respuesta_hash[:numero] = codigo_alfabetico.present? ? "#{codigo_numerico}-#{codigo_alfabetico}" : "#{codigo_numerico}"
            respuesta_hash[:codigo_numerico] = codigo_numerico
            respuesta_hash[:codigo_alfabetico] = codigo_alfabetico
            respuesta_hash[:ultima_fecha] = ultima_fecha
          end
        end
      else
        if numero_ingreso_posterior > 1
          respuesta_hash[:codigo_numerico] = numero_ingreso_posterior.to_i - 1
        else
          respuesta_hash[:tipo_respuesta] = "alerta"
          respuesta_hash[:mensaje] = "No se puede introducir un ingreso para la fecha, por favor contactese con el administrador del sistema."
        end
      end
    end
    respuesta_hash
  end

end

app/controllers/ingresos_controller.rb
class IngresosController < ApplicationController
  load_and_authorize_resource
  before_action :set_ingreso, only: [:show, :edit, :update, :destroy]

  # GET /ingresos
  def index
    if params[:barcode].present?
      barcode = params[:barcode]
      activos = Asset.buscar_por_barcode(barcode)
      render json: activos, root: false
    else
      format_to('ingresos', IngresosDatatable)
    end
  end

  # GET /ingresos/1
  def show
    @activos = @ingreso.assets.order(:code)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Ingreso #{@ingreso.nota_entrega_fecha}".parameterize,
               disposition: 'attachment',
               template: 'ingresos/show.html.haml',
               layout: 'pdf.html',
               page_size: 'Letter',
               # show_as_html: params[:debug].present?,
               margin: view_context.margin_pdf,
               header: { html: { template: 'shared/header.pdf.haml' } },
               footer: { html: { template: 'shared/footer.pdf.haml' } }
      end
    end
  end

  # GET /ingresos/new
  def new
    @ingreso = Ingreso.new
  end

  # GET /ingresos/1/edit
  def edit
    render 'new'
  end

  # POST /ingresos
  def create
    @ingreso = current_user.ingresos.new(ingreso_params)
    respond_to do |format|
      if @ingreso.save
        format.html { redirect_to @ingreso, notice: 'Ingreso creado exitosamente' }
        format.json { render json: @ingreso, status: :created }
      else
        format.html { render :new }
        format.json { render json: @ingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingresos/1
  def update
    respond_to do |format|
      if @ingreso.update(ingreso_params)
        format.html { redirect_to @ingreso, notice: t('general.updated', model: Ingreso.model_name.human) }
        format.js
      else
        format.html { render action: 'new' }
      end
    end
  end

  def obt_cod_ingreso
    resultado = Hash.new
    if params[:d].present?
      fecha = params[:d].to_date
      if params[:n].present?
        nota_ingreso = Ingreso.find(params[:n])
        unless nota_ingreso.numero.present?
          resultado = Ingreso.obtiene_siguiente_numero_ingreso(fecha)
        end
      else
        resultado = Ingreso.obtiene_siguiente_numero_ingreso(fecha)
      end
      if resultado[:tipo_respuesta] == 'confirmacion'
        resultado[:titulo] = "Confirmación de Ingreso"
      elsif resultado[:tipo_respuesta] == 'alerta'
        resultado[:titulo] = "Alerta de Ingreso"
      end
    end
    render json: resultado, root: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingreso
      @ingreso = Ingreso.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ingreso_params
      params.require(:ingreso).permit(:numero, :supplier_id, :factura_numero, :factura_autorizacion, :factura_fecha, :nota_entrega_numero, :nota_entrega_fecha, :c31_numero, :c31_fecha, :total, :observacion, asset_ids: [])
    end
end

app/views/ingresos/_editar.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-editar-nota-entrada"}
  .modal-dialog
    .modal-content
      = form_for :ingreso, url: ingresos_path + '/{{id}}', class: 'form-horizontal', data: {id: "{{id}}"} do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
          %h4.modal-title Editar nota de ingreso
        .modal-body
          = hidden_field_tag '_method', 'PUT'
          .form-group
            %label.col-sm-4.control-label Nro nota ingreso
            .col-sm-8
              = f.text_field "numero", value: "{{numero}}", class: 'form-control nro-nota-ingreso-select', autofocus: true
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}
            %span.glyphicon.glyphicon-ban-circle
            = t('general.btn.cancel')
          %button.btn.btn-primary{type: 'submit'}
            %span.glyphicon.glyphicon-floppy-disk
            = t('general.btn.save')

app/views/ingresos/_ingreso.html.haml
- r = ingreso
%td(class="nowrap sorting_1")= r.factura_fecha.present? ? I18n.l(r.factura_fecha) : ''
%td(class="")= r.numero
%td(class="")= r.supplier_name
%td(class="")= r.user_name
%td(class="")= number_with_delimiter(r.total)
%td(class="")= r.nota_entrega_fecha.present? ? I18n.l(r.nota_entrega_fecha) : ''
%td(class="nowrap")
  = raw(links_actions(r, 'ingreso'))
  = link_to(content_tag(:span, "", class: 'glyphicon glyphicon-sort-by-order'), '#editar', class: 'btn btn-info btn-xs editar-nota-entrada', title: 'Establecer número de nota de entrada', data: {"nota-entrada" => r.as_json}, id: dom_id(r))

app/views/ingresos/_ingreso_modal.html.haml
%script{ id: 'confirmar-ingreso-tpl', type: 'text/html' }
  .modal-header{ style: 'margin-bottom: 5px;' }
  .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-confirmar-ingreso"}
    .modal-dialog
      .modal-content
        = form_for :note_entry, url: "", class: 'form-horizontal', data: "" do |f|
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
            %h4.modal-title {{{titulo}}}
          .modal-body
            .form-group
              %p
                Se está introduciendo un ingreso con fecha anterior al
                %strong {{{ultima_fecha}}}
                , la numeración asignada será la siguiente:
              %h2.text-center
                {{{numero}}}
              %p
                Es necesario especificar una observación:
              .form-group
                = text_area_tag "modal_observacion", '', class: 'form-control'
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}
              %span.glyphicon.glyphicon-ban-circle
              = t('general.btn.cancel')
            %button.btn.btn-primary{type: 'submit'}
              %span.glyphicon.glyphicon-ok
              = t('general.btn.aceptar')

%script{ id: 'alerta-ingreso-tpl', type: 'text/html' }
  .modal-header{ style: 'margin-bottom: 5px;' }
  .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-alerta-ingreso"}
    .modal-dialog
      .modal-content
        = form_for :note_entry, url: "", class: 'form-horizontal', data: "" do |f|
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
            %h4.modal-title {{{titulo}}}
          .modal-body
            .form-group
              %p
                No se puede crear el ingreso con fecha {{{fecha}}}, porque el sistema no puede asignar automáticamente la numeración:
            .form-group
              %table.table.table-bordered
                %thead
                  %tr
                    %th Número
                    %th Fecha
                %tbody
                  %tr
                    %td {{{numero_ingreso_anterior}}}
                    %td {{{fecha_ingreso_anterior}}}
                  %tr.danger
                    %td
                      %strong ?
                    %td {{{fecha}}}
                  %tr
                    %td {{{numero_ingreso_posterior}}}
                    %td {{{fecha_ingreso_posterior}}}
          .modal-footer
            %button.btn.btn-primary{type: 'submit'}
              %span.glyphicon.glyphicon-ok
              = t('general.btn.aceptar')

app/views/ingresos/_ingresos.html.haml
%th= t("activerecord.attributes.ingreso.numero")
%th= t("activerecord.attributes.ingreso.factura_fecha")
%th= t("activerecord.attributes.ingreso.factura_numero")
%th= t("activerecord.attributes.ingreso.supplier")
%th= t("activerecord.attributes.ingreso.telefono")
%th= t("activerecord.attributes.ingreso.users")
%th= t("activerecord.attributes.ingreso.total")
%th= t("activerecord.attributes.ingreso.nota_entrega_fecha")

app/views/ingresos/index.pdf.haml
.title_pdf
  %h3= t("#{controller_name}.title.title")

%table.table.table-condensed.table-bordered.valorado
  %thead
    %tr
      %th.text-center Nro
      %th= t("activerecord.attributes.ingreso.numero")
      %th.text-center= t("activerecord.attributes.ingreso.factura_fecha")
      %th.text-center= t("activerecord.attributes.ingreso.factura_numero")
      %th= t("activerecord.attributes.ingreso.supplier")
      %th= t("activerecord.attributes.ingreso.telefono")
      %th= t("activerecord.attributes.ingreso.users")
      %th.text-right= t("activerecord.attributes.ingreso.total")
      %th.text-center= t("activerecord.attributes.ingreso.nota_entrega_fecha")
  %tbody
    - @array.each_with_index do |ingreso, index|
      %tr
        %td.text-center= index + 1
        %td= ingreso.numero
        %td.text-center= ingreso.factura_fecha.present? ? I18n.l(ingreso.factura_fecha) : ''
        %td= ingreso.factura_numero
        %td= ingreso.supplier_name
        %td= ingreso.telefono_proveedor
        %td= ingreso.user_name
        %td.text-right= number_with_delimiter(ingreso.total)
        %td.text-center= ingreso.nota_entrega_fecha.present? ? I18n.l(ingreso.nota_entrega_fecha) : ''
    - if @array.present?
      %tr
        %th.text-right{colspan: 5} TOTAL
        %th.text-right
          = number_with_delimiter(@array.inject(0) { |s, ingreso| s + ingreso.total})
        %th

app/views/ingresos/show.html.haml
- unless is_pdf?
  .page-header
    .pull-right
      = link_to edit_ingreso_path(@ingreso), class: 'btn btn-primary' do
        %span.glyphicon.glyphicon-edit
        = t("general.btn.edit")
      = link_to ingreso_path(@ingreso, format: :pdf), class: 'btn btn-info' do
        %span.glyphicon.glyphicon-print
        Imprimir PDF
      = link_to ingresos_path, class: 'btn btn-default' do
        %span.glyphicon.glyphicon-list
        = t("ingresos.title.title")

    %h2 Ingreso de Activos Fijos Nro. #{@ingreso.obtiene_numero}

- lista_de_campos = listar_campos(@activos)

- if is_pdf?
  .row{data: {action: 'devolution'}}
    .col-md-12
      %h3
        .text-left.proceeding-title Nro. #{@ingreso.obtiene_numero}
        .text-center Ingreso de Activos Fijos
      - if @ingreso.factura_fecha.present?
        %p
          .text-center
            Fecha de Incorporación: #{I18n.l @ingreso.factura_fecha}

%table.table.table-bordered.table-striped.table-hover.table-condensed.valorado
  %thead
    %tr
      %th.text-center Nro
      %th.text-center Código
      - lista_de_campos.each do |campo|
        %th= Ingreso.human_attribute_name(campo)
      %th.number.nowrap Precio Unit.
  %tbody
    - @activos.each_with_index do |activo, index|
      %tr
        %td.text-center= index + 1
        %td.text-center{title: activo.barcode}= activo.barcode
        - lista_de_campos.each do |campo|
          %td= activo[campo]
        %td.number= number_with_delimiter activo.precio
    %tr
      %th{ colspan: lista_de_campos.length+1 }
      %th.number TOTAL
      %th.number= number_with_delimiter @ingreso.total

%table.table.table-bordered.table-condensed.valorado{ class: "#{is_pdf? ? 'margen' : 'table-striped'}" }
  %thead
    %tr
      %th.col-md-6.col-sm-7.col-xs-8 Datos proveedor
      %th.col-md-6.col-sm-5.col-xs-4 Firma Activos Fijos
  %tbody
    %tr
      %td
        %table.table-condensed
          %tbody
            - if @ingreso.supplier_name.present?
              %tr
                %th.text-right Proveedor
                %td= @ingreso.supplier_name
            - if @ingreso.supplier_nit.present?
              %tr
                %th.text-right NIT
                %td= @ingreso.supplier_nit
            - if @ingreso.factura_numero.present?
              %tr
                %th.text-right Factura No
                %td= @ingreso.factura_numero
            - if @ingreso.factura_autorizacion.present?
              %tr
                %th.text-right Autorización
                %td= @ingreso.factura_autorizacion
            - if @ingreso.factura_fecha.present?
              %tr
                %th.text-right Fecha de factura
                %td= I18n.l @ingreso.factura_fecha
            - if @ingreso.nota_entrega_numero.present?
              %tr
                %th.text-right Número nota de entrega
                %td= @ingreso.nota_entrega_numero
            - if @ingreso.nota_entrega_fecha.present?
              %tr
                %th.text-right Fecha nota de entrega
                %td= I18n.l @ingreso.nota_entrega_fecha
            - if @ingreso.c31_numero.present?
              %tr
                %th.text-right Número C-31
                %td= @ingreso.c31_numero
            - if @ingreso.c31_fecha.present?
              %tr
                %th.text-right Fecha C-31
                %td= I18n.l @ingreso.c31_fecha
            - if @ingreso.observacion.present?
              %tr
                %th.text-right Observación
                %td= @ingreso.observacion

      %td

= fecha_impresion if is_pdf?

app/views/ingresos/update.js.haml
var $tr = $("##{dom_id(@ingreso)}").closest('tr');

$tr.html("#{ j render @ingreso }");
$tr.addClass('warning');